theme: jekyll-theme-cayman
title: "Devrim Nesipoglu Progress Journal"
description: BDA 503 Fall 2017 - MEF University
=======
encoding: UTF-8
>>>>>>> eb761fb87dd144279b8809cd08e1acca97957e7a


